# Generated by Django 3.2 on 2023-04-28 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230428_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
    ]
